global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
    
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node_exporter:9100']    

  - job_name: 'mapfs_cloud'
    static_configs:
    - targets: ['mapfs-cloud:8011']

  - job_name: 'mapfs_gateway'
    static_configs:
    - targets: ['mapfs-gateway:8010']

  - job_name: 'mapfs_device'
    static_configs:
    - targets: ['mapfs-device:8012']

  - job_name: locust
    scrape_interval: 15s
    static_configs:
    - targets:
      - locust-metrics-exporter:9646